server:
    port: 9600

spring:
  data:
    mongodb:
      host: mongod-vb0x.local
      port: 27017
      database: blog_db
      username: blog_usr

logging:
  level:
    org.springframework.data: debug